language: php

php:
  - 7.1

env:
  - COMPOSER_MEMORY_LIMIT=-1

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - composer install --no-interaction --prefer-dist

script:
  - make phpcs
  - make phpstan
  - make codeception

after_success:
  - vendor/bin/php-coveralls
