<?php

namespace FondOfSpryker\Zed\MimicCustomerAccount;

use Spryker\Zed\Kernel\AbstractBundleDependencyProvider;
use Spryker\Zed\Kernel\Container;

class MimicCustomerAccountDependencyProvider extends AbstractBundleDependencyProvider
{
    /**
     * @param \Spryker\Zed\Kernel\Container $container
     *
     * @return \Spryker\Zed\Kernel\Container
     */
    public function provideBusinessLayerDependencies(Container $container)
    {
        return parent::provideBusinessLayerDependencies($container); // TODO: Change the autogenerated stub
    }
}
